# Generated by Django 4.1 on 2023-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_type_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('drinks', 'drinks'), ('entrees', 'entrees'), ('treats', 'treats')], default='', max_length=60),
        ),
    ]
