# Generated by Django 4.1 on 2023-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(choices=[('entrees', 'entrees'), ('appetizers', 'appetizers'), ('treats', 'treats'), ('drinks', 'drinks')], default='', max_length=60),
        ),
    ]
