# Generated by Django 4.1 on 2023-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profiles_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='text',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
